name: attendencemanagement
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_auth: ^5.4.2
  firebase_ui_auth: ^1.16.1
  firebase_core: ^3.11.0
  cloud_firestore: ^5.6.3
  firebase_storage: ^12.4.2
  firebase_database: ^11.3.2
  flutter_animate: ^4.5.0
  flutter_slidable: ^3.1.2
  intl: ^0.19.0
  animate_do: ^3.3.0
  table_calendar: ^3.1.3
  fl_chart: ^0.63.0
  month_picker_dialog: ^6.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
